### ISSUE TITLE
Save button does not work

### ISSUE THREAD

**Issue by celalgorgun** [OscarMo10/ClassroomAssignmentWpf#12]
![back and save doesnt work](https://user-images.githubusercontent.com/25208991/38762403-34b36f4c-3f51-11e8-95fc-4614007c7440.PNG)

**Comment by celalgorgun** [comment]
It could be "back" or "cancel" button to go back to classes. Otherwise you cant do anything else and you have to close to program.

**Comment by OscarMo10** [comment]
Assignment updates the course automatically. A back button on the top right return the user to the main page.
